<a href="https://colab.research.google.com/github/TheSpaceMan915/Artificial-Intelligence/blob/main/Lab2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторная работа №2   Колычев Никита   ВПР34**

#**1.  Найти индексы ненулевых элементов в заданном массиве.**

In [ ]:
import numpy as np

arr_numbers = np.array([5,0,2,6,0,0,10,0])
indexes = np.where(arr_numbers == 0)

print(indexes)

(array([1, 4, 5, 7]),)



#**2.  Создать nxn единичную матрицу.**

In [ ]:
matrix = np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



#**3.  Создать массив nxnxn со случайными значениями**

In [ ]:
n = 5

arr_rands = np.random.randint(10, size=(n,n,n))
print(arr_rands)

[[[6 7 5 4 9]
  [9 2 9 1 8]
  [3 5 8 5 0]
  [1 5 9 6 3]
  [2 6 2 8 1]]

 [[1 7 0 3 3]
  [5 9 7 0 5]
  [9 2 2 1 4]
  [9 2 4 1 2]
  [8 8 4 0 6]]

 [[4 5 8 1 2]
  [4 7 9 9 6]
  [3 7 5 2 2]
  [0 5 4 6 7]
  [0 0 9 5 1]]

 [[1 1 3 5 4]
  [7 0 3 4 6]
  [6 9 2 3 4]
  [1 4 2 6 3]
  [2 1 0 7 3]]

 [[3 8 9 3 2]
  [7 0 8 8 2]
  [8 1 0 7 1]
  [9 1 8 1 9]
  [6 4 0 8 5]]]


#**4.  Создать вектор (одномерный массив) размера n, заполненный нулями**

In [ ]:
size = 4

arr_zeroes = np.zeros(size)
print(arr_zeroes)

[0. 0. 0. 0.]


#**5.  Создать вектор размера n, заполненный нулями, но пятый элемент равен 1**

In [ ]:
size = 7

arr_numbers = np.zeros(size)
arr_numbers[4] = 1

print(arr_numbers)

[0. 0. 0. 0. 1. 0. 0.]


#**6.  Создать вектор со значениями от n до m**

In [ ]:
n = 4
m = 9

arr_numbers = np.arange(n,m)
print(arr_numbers)

[4 5 6 7 8]


#**7. Развернуть одномерный массив (первый становится последним)**

In [ ]:
arr_numbers = np.array(["cat","coala","tea"])

arr_reversed = np.flip(arr_numbers)
print(arr_reversed)

['tea' 'coala' 'cat']


#**8.  Создать матрицу с 0 внутри, и 1 на границах**

In [ ]:
size = 7

# создаю матрицу из единиц
arr_ones = np.ones((size,size))

arr_ones[1:-1,1:-1] = 0
print(arr_ones)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#**9.  Создать nxn матрицу и заполнить её в шахматном порядке**

In [ ]:
# создаю матрицу
n = 4
matrix = np.random.randint(1,10, size=(n,n))

# заполняю матрицу нулями с помощью срезов
matrix[0:1,::2] = 0
matrix[1:2,1::2] = 0
matrix[2:3,::2] = 0
matrix[3:4,1::2] = 0

print(matrix)

[[0 7 0 2]
 [5 0 1 0]
 [0 5 0 9]
 [5 0 4 0]]


#**10.  Заменить максимальный элемент на ноль**

In [ ]:
# создаю массив
arr_numbers = np.array([5,3,7,8,4,2,11])
print("Изначальный массив: ", arr_numbers)

# заменяю максимальный элемент на ноль
index_max = np.argmax(arr_numbers)
arr_numbers[index_max] = 0

print("Измененный массив: ", arr_numbers)

Изначальный массив:  [ 5  3  7  8  4  2 11]
Измененный массив:  [5 3 7 8 4 2 0]


#**11.  Найти ближайшее к заданному значению число в заданном массиве**

In [ ]:
# инициализирую число и массив
number = 11
arr_numbers = np.array([5,3,4,50,10])

# ищу индекс числа
arr_abs_numbers = np.abs(arr_numbers - number)
index_number = arr_abs_numbers.argmin()

print("Индекс: ", index_number)
print("Число: ", arr_numbers[index_number])

Индекс:  4
Число:  10


#**12.  Дан четырехмерный массив, посчитать сумму по последним двум осям**

In [ ]:
# создаю массив
arr_numbers = np.random.randint(10, size=(2,3,3,2))

print("Изначальный массив:")
print(arr_numbers)

# изменяю форму массива
arr_reshaped = arr_numbers.reshape(arr_numbers.shape[:-2] + (-1,))

print()
print("Измененный массив:")
print(arr_reshaped)

# считаю сумму
axes_sum = arr_reshaped.sum(axis=-1)

print()
print("Сумма осей:")
print(axes_sum)

Изначальный массив:
[[[[4 1]
   [5 7]
   [5 4]]

  [[6 8]
   [3 3]
   [2 7]]

  [[4 2]
   [5 0]
   [1 4]]]


 [[[6 2]
   [3 6]
   [6 3]]

  [[5 6]
   [4 0]
   [7 9]]

  [[2 5]
   [4 2]
   [5 4]]]]

Измененный массив:
[[[4 1 5 7 5 4]
  [6 8 3 3 2 7]
  [4 2 5 0 1 4]]

 [[6 2 3 6 6 3]
  [5 6 4 0 7 9]
  [2 5 4 2 5 4]]]

Сумма осей:
[[26 29 16]
 [26 31 22]]


#**13.  Определить, есть ли в двумерном массиве нулевые столбцы**

In [ ]:
# создаю массив
arr_numbers = np.array([[3,5,0],[2,6,0]])

# ищу столбец с нулями
res = (~arr_numbers.any(axis=0)).any()
print(res)

True


#**14.  Отнять среднее из каждой строки в матрице**

In [ ]:
# создаю матрицу
n = 4
matrix = np.random.randint(1,10, size=(n,n))

print("Изначальная матрица: ")
print(matrix)

# вычитаю среднее знач
matrix_res = matrix - matrix.mean(axis = 1, keepdims = True)

print()
print("Итоговая матрица: ")
print(matrix_res)

Изначальная матрица: 
[[3 7 3 9]
 [6 9 3 5]
 [4 6 4 1]
 [3 1 4 6]]

Итоговая матрица: 
[[-2.5   1.5  -2.5   3.5 ]
 [ 0.25  3.25 -2.75 -0.75]
 [ 0.25  2.25  0.25 -2.75]
 [-0.5  -2.5   0.5   2.5 ]]


#**15. Создайте вектор с элементами от 10 до 50**

In [ ]:
arr_numbers = np.arange(10,50)
print(arr_numbers)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#**16. Создайте матрицу (5, 5), заполненую от 0 до 6**

In [ ]:
n = 5
matrix = np.random.randint(0,6,(n,n))

print(matrix)

[[2 1 2 2 4]
 [4 2 3 4 1]
 [5 5 0 2 2]
 [1 4 4 2 3]
 [1 5 1 5 0]]


#**17. Умножьте матрицу размерности (5, 3) на (3, 2)**

In [ ]:
matrix_one = np.random.randint(0,10,(5,3))
matrix_two = np.random.randint(0,10,(3,2))


print("matrix_one:")
print(matrix_one)
print()
print("matrix_two:")
print(matrix_two)

# умножаю матрицы
matrix_res = np.dot(matrix_one,matrix_two)


print()
print("matrix_res:")
print(matrix_res)

matrix_one:
[[3 7 1]
 [7 8 3]
 [9 6 6]
 [6 1 5]
 [5 5 1]]

matrix_two:
[[3 5]
 [9 5]
 [0 3]]

matrix_res:
[[72 53]
 [93 84]
 [81 93]
 [27 50]
 [60 53]]


#**18. Создайте матрицу (10, 10) так, чтобы на границе были 0, а внутри 1**

In [ ]:
size = 10

# создаю матрицу из нулей
arr_ones = np.zeros((size,size))

arr_ones[1:-1,1:-1] = 1
print(arr_ones)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#**19. Для заданного числа найдите ближайший к нему элемент в векторе**

In [ ]:
# инициализирую число и массив
print("Введите число:")
number = int(input())
arr_numbers = np.random.randint(1,100, size=10)


print()
print("Массив:")
print(arr_numbers)


# ищу индекс числа
arr_abs_numbers = np.abs(arr_numbers - number)
index_number = arr_abs_numbers.argmin()


print()
print("Индекс: ", index_number)
print("Число: ", arr_numbers[index_number])

Введите число:
7

Массив:
[16 17 81  7 10 43 15  1  3 85]

Индекс:  3
Число:  7


# **20. Дан трёхмерный массив "Цветное изображение", содержащий изображение, размера (height, width, numChannels), а также вектор коэффициентов длины numChannels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). Реальное изображение не считываем, заполняем трехмерный массив случайными значениями. Преобразуйте цветное изображение в оттенки серого, использовав коэффициенты np.array([0.299, 0.587, 0.114]).**

In [ ]:
# инициализируем переменные и массивы
width = 4
height = 3
num_channels = 3
arr_channels = np.array([0.299, 0.587, 0.114])
arr_image = np.random.rand(width, height, num_channels)


print("Изначальное изображение: ")
print(arr_image)


# преобразую цветное изображение в серые оттенки
for channel in arr_channels: 
  arr_image *= channel


print()
print("Серое изображение:")
print(arr_image)

Изначальное изображение: 
[[[0.27817391 0.20335881 0.04486701]
  [0.85779575 0.85362183 0.40749142]
  [0.9795918  0.85575116 0.11517586]]

 [[0.81416889 0.78643151 0.85011634]
  [0.59863759 0.08900992 0.91923116]
  [0.09890803 0.17569731 0.74144196]]

 [[0.14408199 0.04209116 0.16149956]
  [0.29844461 0.10535719 0.32035243]
  [0.76065139 0.47932673 0.53969439]]

 [[0.79676305 0.33200734 0.91517872]
  [0.38540275 0.50624007 0.99283246]
  [0.81470793 0.0387824  0.85080928]]]

Серое изображение:
[[[0.00556584 0.0040689  0.00089772]
  [0.01716319 0.01707968 0.00815328]
  [0.01960014 0.01712228 0.00230449]]

 [[0.01629028 0.0157353  0.01700954]
  [0.01197783 0.00178095 0.01839242]
  [0.001979   0.00351544 0.01483513]]

 [[0.00288286 0.00084218 0.00323136]
  [0.00597142 0.00210804 0.00640977]
  [0.01521948 0.0095906  0.01079847]]

 [[0.01594202 0.00664296 0.01831134]
  [0.00771132 0.0101291  0.01986507]
  [0.01630107 0.00077598 0.0170234 ]]]
